### ISSUE TITLE
Bug: Manifest generation uses a wrong kubeconfig for the cloud-config

### ISSUE THREAD

**Issue by PatrickLaabs** [rancher-sandbox/cluster-api-provider-harvester#43]
**What happened:**
When running the `clusterctl generate cluster --from https://github.com/rancher-sandbox/cluster-api-provider-harvester/blob/v0.1.2/templates/cluster-template-rke2.yaml -n ${CLUSTER_NAMESPACE} ${CLUSTER_NAME} > harvester-rke2-clusterctl.yaml` the generated Manifest has some weird and wrong kubeconfig for the cloud-config, which will be placed in here:
https://github.com/rancher-sandbox/cluster-api-provider-harvester/blob/main/templates/cluster-template-rke2.yaml#L568

One might have to manually overwrite the string to the desired base64 string of the harvester kubeconfig.

**What did you expect to happen:**

A correct pasting of the base64 encoded kubeconfig 

**How to reproduce it:**

- Create a kind cluster
- clusterctl init
- run `clusterctl generate cluster --from https://github.com/rancher-sandbox/cluster-api-provider-harvester/blob/v0.1.2/templates/cluster-template-rke2.yaml -n ${CLUSTER_NAMESPACE} ${CLUSTER_NAME} > harvester-rke2-clusterctl.yaml`

**Anything else you would like to add:**
I did not find the cause of this issue adhoc, but I'll dig later into it.

**Environment:**

- rke provider version:
- OS (e.g. from `/etc/os-release`):

**Comment by belgaied2** [comment]
This should be solved as of commir 4fe74d12e8790ffe838cd25403048d4d721c8660.
