### ISSUE TITLE
The NetworkName is static and cannot be changed

### ISSUE THREAD

**Issue by firecyberice** [rancher-sandbox/cluster-api-provider-harvester#5]
First thank you for this capi for harvester provider.

As you can see [here](https://github.com/rancher-sandbox/cluster-api-provider-harvester/blob/07d0b61f34a8277c0b8eac620dcd52e757e14b5b/controllers/harvestermachine_controller.go#L616C2-L616C3) the NetworkName for new VMs is hardcoded to `vlan1` which makes it impossible to use a different NetworkName.

At least this should be mentioned in the README as a requirement. :smiley: 

I am currently not really sure if additional networks are used at all, if someone extends that list.
- https://github.com/rancher-sandbox/cluster-api-provider-harvester/blob/07d0b61f34a8277c0b8eac620dcd52e757e14b5b/samples/rke2/example.yaml#L120
- https://github.com/rancher-sandbox/cluster-api-provider-harvester/blob/07d0b61f34a8277c0b8eac620dcd52e757e14b5b/samples/rke2/example.yaml#L140
- https://github.com/rancher-sandbox/cluster-api-provider-harvester/blob/07d0b61f34a8277c0b8eac620dcd52e757e14b5b/samples/kubeadm/example.yaml#L134
- https://github.com/rancher-sandbox/cluster-api-provider-harvester/blob/07d0b61f34a8277c0b8eac620dcd52e757e14b5b/samples/kubeadm/example.yaml#L154

**Comment by belgaied2** [comment]
@firecyberice Thank you so much for the issues, I will try to take a look at them ASAP (for now, I am the only one working on this on my free time, but hoping to onboard more people if I get some more traction :) )

**Comment by belgaied2** [comment]
Fixed by 76a6e88dcdc1fe51be36bee46b7af3765a8639d8
